# Generated by Django 5.0.4 on 2026-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0002_alter_composeapp_compose_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composeapp',
            name='current_commit_sha',
            field=models.CharField(blank=True, help_text='SHA du commit actuellement déployé (capturé après chaque déploiement)', max_length=40),
        ),
    ]
