# Generated by Django 5.0.4 on 2026-03-25 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0003_composeapp_current_commit_sha'),
    ]

    operations = [
        migrations.AddField(
            model_name='composeapp',
            name='webhook_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token secret pour déclencher un redéploiement depuis GitHub Actions', unique=True),
        ),
    ]
