# Generated by Django 5.0.4 on 2026-03-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx_manager', '0002_nginxvhost_container_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nginxvhost',
            name='route_overrides',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
