# Generated by Django 5.0.4 on 2026-03-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubOAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('configured_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GitHub OAuth Config',
            },
        ),
    ]
